export const PREFIX_SYNONYMS: Record<string, string[]> = {
  ACCT: ["accounting", "acct", "financial accounting", "managerial accounting", "business"],
  ACTS: ["actuarial science", "actuarial", "risk", "probability", "statistics"],
  AHST: ["art history", "art", "history of art"],
  AHTC: ["arts humanities technology", "aht", "digital arts", "creative tech"],
  AMS:  ["american studies", "american culture", "us culture"],
  ANGM: ["animation", "games", "game design", "3d animation"],
  ARAB: ["arabic", "arabic language"],
  ARHM: ["arts and humanities", "humanities", "liberal arts"],
  ARTS: ["art", "studio art", "drawing", "painting"],
  ATCM: ["arts technology", "media", "digital media", "communication"],
  BA:   ["business administration", "business", "management"],
  BBSU: ["behavioral and brain sciences", "bbs", "neuroscience", "psychology"],
  BCOM: ["business communication", "presentations", "professional communication"],
  BIOL: ["biology", "bio", "life science"],
  BIMS: ["biomedical sciences", "pre med", "bio med"],
  BIS:  ["interdisciplinary studies", "ids", "interdisciplinary"],
  BLAW: ["business law", "law", "legal", "commercial law"],
  BMEN: ["biomedical engineering", "bme", "medical devices"],
  BPS:  ["business policy", "strategy", "business strategy"],
  BUAN: ["business analytics", "data analytics", "analytics", "data science"],
  CE:   ["computer engineering", "hardware", "embedded systems"],
  CGS:  ["cognitive science", "cognition", "mind", "brain"],
  CHEM: ["chemistry", "chem", "chemical"],
  CHIN: ["chinese", "mandarin"],
  CLDP: ["child learning", "development", "child development"],
  COMM: ["communication", "speech", "media studies"],
  CPSY: ["clinical psychological science", "clinical psych", "psychology"],
  CRIM: ["criminology", "crime", "criminal justice"],
  CRWT: ["creative writing", "writing", "fiction", "poetry"],
  CS:   ["computer science", "artificial intelligence", "programming", "machine learning", "software", "algorithms", "data"],
  CYBR: ["cybersecurity", "security", "infosec", "risk management"],
  DANC: ["dance", "performance", "choreography"],
  ECON: ["economics", "econ", "microeconomics", "macroeconomics"],
  ECS:  ["engineering and computer science", "ecs", "engineering", "cs"],
  ECSC: ["engineering coop", "ecs coop", "internship"],
  ED:   ["education", "teaching", "teacher prep"],
  EE:   ["electrical engineering", "ee", "circuits", "signal processing"],
  ENGR: ["engineering", "engineer"],
  ENGY: ["energy management", "energy", "oil gas", "power industry"],
  ENTP: ["entrepreneurship", "innovation", "startup", "business"],
  ENVR: ["environmental science", "environmental", "ecology"],
  EPCS: ["epics", "engineering projects", "community service"],
  EPPS: ["economic political policy sciences", "policy", "public policy"],
  FILM: ["film", "cinema", "movie studies", "screen studies"],
  FIN:  ["finance", "financial", "investment", "corporate finance"],
  FREN: ["french", "french language"],
  GEOG: ["geography", "maps", "human geography"],
  GEOS: ["geosciences", "geology", "earth science"],
  GERM: ["german", "german language"],
  GISC: ["geospatial information", "gis", "mapping"],
  GOVT: ["government", "politics", "political science"],
  GST:  ["gender studies", "gender", "feminist studies"],
  HIND: ["hindi", "hindi language"],
  HIST: ["history"],
  HLTH: ["health care studies", "health", "pre health"],
  HMGT: ["healthcare management", "health management"],
  HONS: ["honors", "honors college"],
  HUMA: ["humanities", "liberal arts"],
  IMS:  ["international management", "global business", "international business"],
  IPEC: ["international political economy", "political economy", "global politics"],
  ISAE: ["interdisciplinary", "arts technology", "emerging communication"],
  ISAH: ["interdisciplinary", "arts and humanities"],
  ISEC: ["interdisciplinary", "electrical engineering", "computer science"],
  ISIS: ["interdisciplinary studies", "ids"],
  ISNS: ["interdisciplinary natural science", "science", "math"],
  ITSS: ["information technology", "it", "systems", "it management"],
  JAPN: ["japanese", "japanese language"],
  KORE: ["korean", "korean language"],
  LANG: ["languages", "foreign language"],
  LATS: ["latin american studies", "latam"],
  LIT:  ["literature", "lit", "reading", "english studies"],
  MATH: ["mathematics", "math", "calculus", "algebra", "analysis"],
  MECH: ["mechanical engineering", "me", "mechanics"],
  MECO: ["managerial economics", "econ", "business economics"],
  MILS: ["military science", "rotc"],
  MKT:  ["marketing", "marketing management", "advertising"],
  MSEN: ["materials science", "materials engineering", "nanomaterials"],
  MUSI: ["music", "music theory", "performance"],
  NATS: ["natural sciences", "science", "core science"],
  NSC:  ["neuroscience", "brain science", "neuro"],
  OBHR: ["organizational behavior", "human resources", "hr", "management"],
  OPRE: ["operations research", "operations", "supply chain", "quantitative methods"],
  PA:   ["public affairs", "public administration"],
  PHIL: ["philosophy", "ethics", "logic"],
  PHIN: ["physical instruction", "pe", "physical education", "fitness"],
  PHYS: ["physics", "phys", "mechanics", "electromagnetism"],
  PORT: ["portuguese", "portuguese language"],
  PPOL: ["public policy", "policy"],
  PSCI: ["political science", "politics", "government"],
  PSY:  ["psychology", "psych", "behavior", "cognition"],
  REAL: ["real estate", "property", "real estate finance"],
  RELS: ["religious studies", "religion"],
  RHET: ["rhetoric", "writing", "composition"],
  RMIS: ["risk management", "insurance", "rmis"],
  SE:   ["software engineering", "se", "software development"],
  SGNL: ["sign language", "american sign language", "asl"],
  SOC:  ["sociology", "society", "social science"],
  SPAN: ["spanish", "spanish language"],
  SPAU: ["speech language pathology", "audiology", "communication disorders"],
  STAT: ["statistics", "stat", "data", "probability"],
  SYSE: ["systems engineering", "systems", "engineering"],
  THEA: ["theatre", "drama", "acting"],
  UNIV: ["university", "core course", "first year"],
  URDU: ["urdu", "urdu language"],
  VIET: ["vietnamese", "vietnamese language"],
  VPAS: ["visual and performing arts", "vpa", "art", "music", "theatre"],
};
