name: Lint and Formatting Check

on: push

jobs:
  main:
    name: Run ESLint + Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Next for ESLint and Prettier
        run: npm install

      - name: Run ESLint
        run: npm run lint:check

      - name: Run Prettier
        run: npm run format:check
